name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}Plugin
api-version: 1.17
depend: [CivModCore, BanStick, ExilePearl]
softdepend: [Votifier]
authors: [Maxopoly]
permissions:
  eg.public:
    default: true
  eg.op:
    default: op
