name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}Plugin
api-version: 1.14
depend: [CivModCore, BanStick]
softdepend: [NuVotifier]
authors: [Maxopoly]
